import React from 'react';
import type { Metadata } from 'next';
import '../style/globals.css';
import NavigationDesktop from '@/components/NavigationDesktop';
import FooterDesktop from '@/components/FooterDesktop';
import NavigationMobile from '@/components/NavigationMobile';
import FooterMobile from '@/components/FooterMobile';
import '@fontsource/poppins';
import '../style/color.css';
import 'normalize.css';
import css from './layout.module.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout(
  {children}: { children: React.ReactNode },
) {
  return (
    <html lang="en">
    <body>
    <header>
      <NavigationDesktop/>
      <NavigationMobile/>
    </header>

    <main className={css.main}>
      {children}
    </main>

    <footer>
      <FooterDesktop/>
      <FooterMobile/>
    </footer>
    </body>
    </html>
  );
}
