import type { Metadata } from 'next';
import './globals.css';
import NavigationDesktop from '@/components/NavigationDesktop';
import FooterDesktop from '@/components/FooterDesktop';
import NavigationMobile from '@/components/NavigationMobile';
import FooterMobile from '@/components/FooterMobile';
import '@fontsource/poppins';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout(
  {children}: { children: React.ReactNode },
) {
  return (
    <html lang="en">
    <body>
    <header>
      <NavigationDesktop/>
      <NavigationMobile/>
    </header>

    {children}

    <footer>
      <FooterDesktop/>
      <FooterMobile/>
    </footer>
    </body>
    </html>
  );
}
