export default [
  'add',
  'add_circle',
  'add_circle_outline',
  'archive',
  'backspace',
  'block',
  'cancel',
  'check',
  'check_circle',
  'check_circle_outline',
  'clear',
  'create',
  'delete',
  'delete_forever',
  'done',
  'done_all',
  'edit',
  'filter_list',
  'help',
  'help_outline',
  'history',
  'info',
  'info_outline',
  'label',
  'link',
  'lock',
  'lock_open',
  'print',
  'refresh',
  'remove',
  'remove_circle',
  'replay',
  'report',
  'save',
  'search',
  'send',
  'settings',
  'share',
  'sort',
  'star',
  'star_border',
  'thumb_down',
  'thumb_up',
  'undo',
  'visibility',
  'visibility_off',
  'warning',

  // Навигация (Navigation)
  'arrow_back',
  'arrow_downward',
  'arrow_drop_down',
  'arrow_drop_up',
  'arrow_forward',
  'arrow_left',
  'arrow_right',
  'arrow_upward',
  'chevron_left',
  'chevron_right',
  'close',
  'expand_less',
  'expand_more',
  'first_page',
  'last_page',
  'menu',
  'more_horiz',
  'more_vert',
  'navigate_before',
  'navigate_next',
  'subdirectory_arrow_left',
  'subdirectory_arrow_right',

  // Коммуникация (Communication)
  'alternate_email',
  'call',
  'call_end',
  'chat',
  'chat_bubble',
  'chat_bubble_outline',
  'comment',
  'contact_mail',
  'contact_phone',
  'email',
  'forum',
  'message',
  'notifications',
  'notifications_active',
  'notifications_none',
  'notifications_off',
  'phone',
  'voicemail',

  // Контент (Content)
  'add_box',
  'content_copy',
  'content_cut',
  'content_paste',
  'create_new_folder',
  'file_copy',
  'file_download',
  'file_upload',
  'filter',
  'flag',
  'forward',
  'gesture',
  'inbox',
  'redo',
  'remove_red_eye',
  'select_all',

  // Устройства (Devices)
  'access_alarm',
  'access_time',
  'battery_alert',
  'battery_charging_full',
  'battery_full',
  'bluetooth',
  'bluetooth_connected',
  'bluetooth_disabled',
  'computer',
  'devices',
  'headset',
  'keyboard',
  'keyboard_arrow_down',
  'keyboard_arrow_left',
  'keyboard_arrow_right',
  'keyboard_arrow_up',
  'laptop',
  'phone_android',
  'phone_iphone',
  'power',
  'power_off',
  'tablet',
  'tv',
  'watch',

  // Файлы (Files)
  'attachment',
  'cloud',
  'cloud_download',
  'cloud_upload',
  'folder',
  'folder_open',
  'folder_shared',
  'insert_drive_file',

  // Места (Places)
  'business',
  'home',
  'location_city',
  'location_on',
  'map',
  'my_location',
  'place',
  'public',
  'room',

  // Социальные (Social)
  'cake',
  'favorite',
  'favorite_border',
  'group',
  'group_add',
  'mood',
  'notifications_active',
  'person',
  'person_add',
  'person_outline',
  'share',
  'thumb_up_alt',

  // Редактор (Editor)
  'border_color',
  'format_align_center',
  'format_align_left',
  'format_align_right',
  'format_bold',
  'format_italic',
  'format_list_bulleted',
  'format_list_numbered',
  'format_quote',
  'format_size',
  'insert_chart',
  'insert_photo',
  'mode_edit',

  // Аппаратное обеспечение (Hardware)
  'cast',
  'desktop_windows',
  'developer_board',
  'device_hub',
  'memory',
  'mouse',
  'router',
  'scanner',
  'security',
  'sim_card',

  // Изображения (Image)
  'add_a_photo',
  'camera',
  'camera_alt',
  'image',
  'photo',
  'photo_camera',
  'photo_library',
  'portrait',
  'slideshow',
] as Array<string>;
